use_frameworks!

platform :ios, '8.0'

target 'LWG_A_Category_Example' do
  pod 'LWG_A_Category', :path => '../'

  target 'LWG_A_Category_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
